async_envs: true
budget: 90
clip_coef: 0.2
cuda: false
ent_coef: 0.05
env_id: AdaptiveFPS-v0
frame_cost: 0.1
gae_lambda: 0.98
gamma: 0.99
learning_rate: 0.0003
map_name: f1_aut
max_grad_norm: 0.5
model_run_name: fast_Std_Std_TAL_f1_aut_6_5_0
num_envs: 16
num_minibatches: 4
num_steps: 512
run_file: TAL_maps
seed: 1
total_timesteps: 15000000
update_epochs: 4
vf_coef: 0.5
